### ISSUE TITLE
Display the file name

### ISSUE THREAD

**Issue by MrTopom** [simlu/voxelshop#141]
Display the name of the file currently edited.

**Comment by simlu** [comment]
A good one! Where do you think it should be displayed?

**Comment by MrTopom** [comment]
I think in the 3D View title would be great. Displaying also <NOT SAVED> message when just created and not saved.

**Comment by simlu** [comment]
Are you thinking in the 3D view? Or maybe next to the menu on the title bar instead?
Reference: https://s17.postimg.org/czinvvm8f/Capture_d_cran_2016_10_31_22_45_48.png

**Comment by MrTopom** [comment]
I just did in the 3D View title, not to have to modify the menu behavior or add a little label space.
https://s11.postimg.org/3uhz8nmcz/Capture_d_cran_2016_11_01_00_25_00.png

**Comment by simlu** [comment]
I like it! Does it work as expected when changing files yet?
Let me know when you have a pull request!

**Comment by MrTopom** [comment]
Yes I tested New, Save, Save As. I just sent the pull request.

**Comment by simlu** [comment]
Nice, I've added some basic comments. Will take a closer look at it tonight!

**Comment by simlu** [comment]
Merged and live with the Java version
