### ISSUE TITLE
Export Colours as Separate Objects/Meshes

### ISSUE THREAD

**Issue by B0073D** [simlu/voxelshop#15]
Can we please add an export option for colours as separate objects? If not separate objects at least separate meshes?

This would allow artist to work with closed meshes. This is especially handy when working with transparent materials or otherwise scattering/transmitting materials.

Some use cases of this would include, water/other liquids, waxes, windows, etc etc. This would allow the required material to be an entirely separate closed mesh and other objects 'touching' this material are closed. ie, not a shell.

A quick programmatic/technical example:
Rough glass left , Glass with absorption middle, Separated right.

![split_example](https://cloud.githubusercontent.com/assets/3069328/19791726/8115c014-9d0f-11e6-885f-b600412d00e2.png)

**Comment by simlu** [comment]
I see. I'm not sure why we need to export all colors as separate meshes though. Wouldn't it be enough to move the material color you want to customize to a separate layer and then export layers as different objects? You can already do that quite efficiently by selecting a voxel, then expanding selection (it think it's ctrl + shift + w) and then clicking "move selection to new layer".

A downside of exporting all colors as separate objects is that the vertex / tri count goes up significantly for colorful objects. In that case it would be highly beneficial to only separate the material you want to customize. 

Please elaborate!

**Comment by B0073D** [comment]
Can you select by that colour everywhere? ie, not just connected but also all other instances of it?

There would be scenarios where these colours are in a few places not just one connected section, if that makes sense.

If you could select all instances of that colour then yes I guess that would do the trick.

**Comment by simlu** [comment]
Yes, that's how it works! Play around with it a little more and see if it's what you need.

**Comment by B0073D** [comment]
Yup that works great. Sorry for wasting your time!

**Comment by simlu** [comment]
No worries! I really need to start a wiki for the program. I think it can help a lot...
