### ISSUE TITLE
Middle mouse Button for dragging the scene around

### ISSUE THREAD

**Issue by funabab** [simlu/voxelshop#155]
I don't know if this can be configured, but i think the middle mouse button should be used by default for dragging the scene around instead of painting voxels.

**Comment by simlu** [comment]
Oh, this isn't working for you? It is working on windows. Mac might bind mouse keys differently. There was an issue for this already (it's closed). Have a look at the commit and how we can make it so that it works on Mac I'd you want!

**Comment by funabab** [comment]
Lol, seems you just assumed my distro. By the i use linux

**Comment by simlu** [comment]
Ah, so few Linux users! Great to have another one here :) I use Ubuntu with xmonad a lot, but windows is still my host for virtualbox. What distribution are you using?

**Comment by funabab** [comment]
I also use Ubuntu :)

**Comment by funabab** [comment]
But i also dual boot windows

**Comment by simlu** [comment]
Great, that should be easy to debug. Will try to get to it soon!

**Comment by simlu** [comment]
So this is actually implemented, but not live yet for the native installers.

**Comment by simlu** [comment]
Please use Java installer for latest version or wait until we update the native installer!

This was implemented here: https://github.com/simlu/voxelshop/issues/39
