### ISSUE TITLE
Rething Shortcuts

### ISSUE THREAD

**Issue by MrTopom** [simlu/voxelshop#157]
The color palette does not receive the keys but the 3D view does and rotates accordingly.

**Comment by simlu** [comment]
I changed the bindings. It's now shift and arrow keys I think. We have to rethink hotkeys and how they should work... Maybe camera keys are only enabled when in one of the 3 view windows? Or only in the main view window?

**Comment by simlu** [comment]
We really need to fix this before doing anything here: https://github.com/simlu/voxelshop/issues/144

**Comment by simlu** [comment]
I think frame shortcuts should be able to collide with global shortcuts and supersede the. That way we can have global undo and still have a frame undo with the same shortcuts for the color palette.

Im also thinking to add a lot more frame shortcuts now that they are much improved... 

Thoughts?

**Comment by simlu** [comment]
I think I want to do this before 1.8 to not have to major releases with changed shortcuts..

**Comment by simlu** [comment]
Anyone got preferences on bindings?

**Comment by simlu** [comment]
Can we get a discussion going here please. What shortcuts do you guys think make sense and which ones don't? I'll propose a different mapping this weekend I think.

**Comment by simlu** [comment]
Making progress here. Do you think the shortcuts for the Tools should stay the same (1,2,3,4,...)?

Need some opinions please!

**Comment by simlu** [comment]
Here are some references btw:
Photoshop: https://www.sitepoint.com/speed-up-your-photoshop-work-with-layer-shortcuts/
Photoshop: https://www.nobledesktop.com/shortcuts/photoshopcs6/mac
JetBrains: https://www.jetbrains.com/help/idea/2016.2/keyboard-shortcuts-you-cannot-miss.html
Blender: https://wiki.blender.org/index.php/Doc:2.4/Reference/Hotkeys/All

Still not sure about the Tool shortcuts...

**Comment by MrTopom** [comment]
I used to manage views side in Blender with those numbers. Even if I have no numeric pad on my laptop.
But then for tools would need something like :
C : Camera
A : Add
R : Remove
...

**Comment by simlu** [comment]
V : View = Camera
C : Create = Add
R : Remove = Delete

Since we use asdqwe for camera interaction

**Comment by simlu** [comment]
Changed it around some more... unless you have any issues it's good to go from my side!

Here are the global shortcuts:
![Image of Global Shortcuts](http://i.imgur.com/2POJXby.png)

**Comment by simlu** [comment]
This is basically done. Good to go @MrTopom?
https://github.com/simlu/voxelshop/pull/192

**Comment by MrTopom** [comment]
I think it should write SHIFT + CTRL + ... instead of SHIFT CTRL + 

And I am not sure about the fact to use 1..9 for the view as this could be more used to view in defined angles in the 3D view with is more frequently necessary.

**Comment by simlu** [comment]
Agreed, lets leave the numbers reserved for something used more. I'll re-add the ctrl back in.

**Comment by simlu** [comment]
Changed it. Can you review pull request again? thanks @MrTopom

**Comment by simlu** [comment]
Done and closing this.
