### ISSUE TITLE
Preview position of mouse

### ISSUE THREAD

**Issue by funabab** [simlu/voxelshop#159]
I love the way voxelshop is designed, pretty standard. But i think you should add a preview of the 3d postion of the mouse while in working grid, cause it only shows when drawing with selection.

**Comment by simlu** [comment]
I'm actually not sure what you mean. There is a preview when you are hovering the mouse?

**Comment by MrTopom** [comment]
If it is the 3D voxel position, the feature is in the develop branch. So will be released next time.

**Comment by simlu** [comment]
Oh! Yes, please try the java installer. That is also the recommended way for using VoxelShop!

**Comment by funabab** [comment]
What did you mean by java installer i downloaded it from the website

**Comment by simlu** [comment]
Please use the Java installer or wait until we update the native installer.

This has been implemented here: https://github.com/simlu/voxelshop/issues/28

**Comment by funabab** [comment]
Ohhhh you mean the jar installer?

**Comment by simlu** [comment]
At the bottom here it says "For All OS", that's the one!
https://blackflux.com/node/11
