### ISSUE TITLE
Change Splash Screen

### ISSUE THREAD

**Issue by funabab** [simlu/voxelshop#160]
This is not an issue actually but will you mind changing the splash screen cause the current one look abit awful.

**Comment by simlu** [comment]
Would love to! You any good with these kind of things? I'd be very happy to change it if we get a decent replacement!

**Comment by funabab** [comment]
We it's depend on what you want

**Comment by simlu** [comment]
Something fun that people like. I don't actually care much about it much. If people think it's better than the current one we'll use it :)

**Comment by MrTopom** [comment]
Should it contain the copyrights at the bottom ?

**Comment by funabab** [comment]
Yes, i also was thinking maybe a mascot should be included

**Comment by funabab** [comment]
MrTopom are you already designing something?

**Comment by MrTopom** [comment]
Not yet but was moving in my head :)

**Comment by funabab** [comment]
Am wondering what the mascot should be, maybe a bird, a monkey or something else.

**Comment by funabab** [comment]
Was thinking about a mascot, came up with a little bird paint shop keeper
![bird]  (https://dl.dropboxusercontent.com/s/9lij9sqpjr9y4a1/snap2016-11-03-10-55-41.png?dl=0) 

File can be downloaded here bird [bird shopkeeper] ( https://dl.dropboxusercontent.com/s/558chrdz60eu049/store_keeper.vsd?dl=0)

**Comment by funabab** [comment]
Make some changes

**Comment by simlu** [comment]
Nice! I like it!

**Comment by MrTopom** [comment]
![spalsh001](https://cloud.githubusercontent.com/assets/21014335/19966570/a0f5e0dc-a1cc-11e6-9c57-1c6d66c60280.png)

**Comment by simlu** [comment]
I like it. Sweet and simple! Thoughts @funabab? 

Is that a font/font file that we can use to generate the version part automatically?

**Comment by funabab** [comment]
Love it too :D simple and sweet...  Good job MrTopom

**Comment by funabab** [comment]
Love the fact that due to its simplicity, it can also be used in different cases

**Comment by MrTopom** [comment]
Yes could generate the splash screen with good version number. The font is free for non commercial usage.

**Comment by simlu** [comment]
Great, mind posting a link here? Thanks!

**Comment by MrTopom** [comment]
Link on what ?

**Comment by simlu** [comment]
To the font or psd file (if you're using ps)

**Comment by MrTopom** [comment]
http://www.urbanfonts.com/fonts/Arcade.htm

I used Inkscape to make the drawing/composition.

**Comment by simlu** [comment]
Just added the new splash screen, you should see it when starting the java version!

**Comment by simlu** [comment]
You guys ok with closing this issue @MrTopom and @funabab ?
