### ISSUE TITLE
Changing of view title to generic names

### ISSUE THREAD

**Issue by funabab** [simlu/voxelshop#162]
Views are currently named XY, XZ etc, maybe remaining it to something generic like Top, Bottom and side view will be helpful for remembering purpose.

**Comment by simlu** [comment]
I've started this by adding Top, Side, Front to the side views already. However we might want to consider changing it everywhere... There is a task for this already here: https://github.com/simlu/voxelshop/issues/25

So I'm closing this as duplicate. Please continue discussion there!
