### ISSUE TITLE
Frame Shortcuts should superseed Global Shortcuts

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#175]
Let's make it so that collision is possible.

**Comment by MrTopom** [comment]
Tools Shortcuts must superseed frame ones.

Tools > Frames > Global

**Comment by simlu** [comment]
I think that is a question of collisions. I think we can get away with displaying warning if there is a collision between a frame and a global shortcut (background yellow). Then set the defaults sane and most people will never change them.

**Comment by simlu** [comment]
Done, will need you to review again @MrTopom 

This will be nice when we get to implementing undo for frame specific actions (e.g. when changing the color palette). The global ctr + z will work, but when pressing it in the color palette it will do the undo there.

Now onto defining what the shortcuts should look like for this release. I'm not too happy with them currently: https://github.com/simlu/voxelshop/issues/157

**Comment by simlu** [comment]
This is basically done. However I think we want to display colliding shortcuts with yellow be. Or do we? Thoughts?

**Comment by simlu** [comment]
So the edit field will be yellow when editing a shortcut with a soft collision (collision between global and frame shortcut), but the field color is the same for all if not editing.

Merged.
