### ISSUE TITLE
Github Pages & Content

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#181]
I'm thinking to move it away from blackflux.com and host it as "github pages". Thoughts?

Reference: https://pages.github.com/

**Comment by simlu** [comment]
This would be really cool as it would mean I could get some help with updating and maintaining the page!

**Comment by MrTopom** [comment]
Good idea.

**Comment by funabab** [comment]
Yeah, cool idea and also maybe a redesign of the page. I suggesting  maybe a big "download for all os" button and another link to native installers, in order to promote java installer download. i should be able to come up with a design proposal (Any time soon) ...

**Comment by simlu** [comment]
Sweet! I'll see how github pages will best work for us and circle back here.

**Comment by kevzettler** [comment]
I'm +1 I use github pages for tons of stuff

**Comment by simlu** [comment]
Should we use Disqus for comments or do we rather not go there?

**Comment by MrTopom** [comment]
There is Adds aspect that is not related to the global open source/free project. But i never use those type of tools.

**Comment by simlu** [comment]
I'm just asking b/c Disqus seems to be supported "out of the box" with the template we are using.

**Comment by simlu** [comment]
There is a preliminary version live here: https://simlu.github.io/voxelshop/

Thank you very much @MrTopom !!

**Comment by simlu** [comment]
Closing this, discussed to be continued here:
https://github.com/simlu/voxelshop/issues/203
