### ISSUE TITLE
VOX not loaded

### ISSUE THREAD

**Issue by MrTopom** [simlu/voxelshop#193]
I have generated a VOX (Magicavoxel) that can be read in Magicavoxel but could not be imported in VoxelShop.

[Gen001.vox.zip](https://github.com/simlu/voxelshop/files/574117/Gen001.vox.zip)

**Comment by simlu** [comment]
Interesting. Did you use any custom settings for the export?

**Comment by MrTopom** [comment]
Found.  Was the palette index not good for my voxels. I put 0 as default index for all but need 1 because of Vox palette mapping.

**Comment by simlu** [comment]
Is there something we should improve here?

**Comment by MrTopom** [comment]
I am not sure we could have index of 0 in normal VOX file.

**Comment by simlu** [comment]
Oh, you generated this file? Not magica?

**Comment by MrTopom** [comment]
I did yes with my program.

**Comment by simlu** [comment]
Ah, that makes sense then. We should possible handle that if magics does, but not very important...
