### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#204]
I've added the here:
https://github.com/simlu/voxelshop/releases/tag/1.8.0

Anything missing or that should be changed? @MrTopom @funabab

**Comment by simlu** [comment]
What should be put up on twitter? This?
`#VoxelShop 1.8 live! Download https://blackflux.com/node/11 and release notes https://github.com/simlu/voxelshop/releases/tag/1.8.0 Native installers to come next weekend.`

**Comment by rubengc** [comment]
You can use URL Shortener to short this urls (also you could see analytics about clicks on this shortened urls)

**Comment by simlu** [comment]
Release notes seems good. Closing this.
