### ISSUE TITLE
Proper use of Bounding Box

### ISSUE THREAD

**Issue by funabab** [simlu/voxelshop#211]
Currently the bounding box is not very much in "use" cause one can still draw outside the bounding box. In reality since voxelart is similar to pixel art and the bounding box should serve as a canvas (like in 2D). It would be nice if bounding box was the only "drawable" portion, not only will it be a good usability improvement, it would also optimize/improve most internal features eg the exporter and #210.

**Comment by rubengc** [comment]
At most I would replace it with an infinite floor where you can draw voxels, I use box wall currently to take height to my project because i can not draw on Y axis (instead of clicking so much on a tower of voxels)

**Comment by funabab** [comment]
That will be a disaster if we implement the face tool, so i think it wrong

**Comment by funabab** [comment]
The best solution is to set a reasonable size as the default bounding box eg 126,  you can then expand it (currently supported)  to fit your needs.

**Comment by rubengc** [comment]
Why face tool is a disaster? How can I expand the bouncing box?

**Comment by funabab** [comment]
In simple term the max size supported  by voxelshop is the max size of an Integer. If we made the ground that size, using the face to fill the ground like in MV will probably crash on most computers. There is an arrow button below the bounding box button,  clicking on the button will show the input for changing the bounding box size,  I wonder why such an important function was hidden behind a button.

**Comment by rubengc** [comment]
this limit comes from Java?

Something that really worries me is VS performance, I tested those days Magica Voxel and I really can build complex voxel art more faster than in VS (more faster, but the result is less efficient for games)

In Voxel Shop a simple project of 400 voxels begins slowing down the program on my computer (i7-4720HQ, nvidia GTX 970M, SSD rom, 16 Gb ram DDR4)

I use PHPStorm commonly (based on Intellij IDEA, built in Java too)

Some years ago they have several performance problems but finally they solve this (I did not followed their development so I do not know how)

Intellij IDEA is open source so probably you can learn something from their repo (how they manage large files or how they manage program task or if they are using some libraries for performance)

Android Studio (by Google) is based on Intellij IDEA too

**Comment by funabab** [comment]
Yeah the limit is from java. Magicavoxel will be faster than voxelshop due to fact that most of it current limitations were due to performance consideration e.g it 126 max size and it was written in c++ (although that doesn't matter much). It's true that VS begins to get slow when working with large models and even Magicavoxel that am running via wine tends to perform better but i think that's due to multiple reasons and i wish simlu  would be able to look into this.

**Comment by rubengc** [comment]
I'm a little lost with performance I do not know how to improve this part, it requires more deep knowledges, but sure with all our help @simlu will find the way to solve this

**Comment by simlu** [comment]
No no no, the issue does not come from Java. There are two parts here:
(1) Data structure
(2) Rendering

Why you are currently experiencing slowness is bc of rendering. I'm using a software renderer to be compatible easily with all os.

The next step then is to change the data structure. That is important for undo / redo operations and for really large objects...

**Comment by simlu** [comment]
Im planning to address rendering first.

**Comment by rubengc** [comment]
Sounds nice @simlu

**Comment by funabab** [comment]
Nice to hear, but the limit i was talking about was Integer.MAX_VALUE.

**Comment by simlu** [comment]
Yeah, that's an implementation detail and not the reason why it's slow. In general you are right, but it's not the limiting factor here.

**Comment by funabab** [comment]
Nooooo,  am not saying that's why it's  slow, am just saying making the default ground size that amount will be unrealistic and will probably cause more issues.

**Comment by simlu** [comment]
There is an implicit limit ~pow(MAX_INT, 1/3)

**Comment by simlu** [comment]
Im not opposed to an infinite ground... Not sure how it would display.

**Comment by funabab** [comment]
Never saw that :D.. Infinite ground? Are you not bothered about performance?

**Comment by simlu** [comment]
Well, by infinite I meant ~pow(MAX_INT, 1/3)

**Comment by rubengc** [comment]
not infinte, but if it follows the camera movement? like side-scrolling games

**Comment by rubengc** [comment]
anyway, I do not know that I can change their size, with this option bounding box is more than done to go

A infinite floor does not needs attention at this moment

**Comment by simlu** [comment]
I'm reworking milestones atm around performance improvements. Closing this as it went way off of topic. Created a new issue here: https://github.com/simlu/voxelshop/issues/216
