### ISSUE TITLE
Roadmap/Milestones

### ISSUE THREAD

**Issue by rubengc** [simlu/voxelshop#213]
We do not know what is the current roadmap or on what your a focused, so you can start targeting "approved" issues to coming versions

**Comment by simlu** [comment]
There are milestones?

**Comment by rubengc** [comment]
I followed the development of [Easy Digital Downloads](https://github.com/easydigitaldownloads/easy-digital-downloads/) 

Normally I use GitLab for work (that have this feature) and I was suppose that GitHub has it too, but if does not have this, you could use a tag as targeted version of some issue/pr

**Comment by simlu** [comment]
Im saying github.com has milestones and I'm already using them...

**Comment by rubengc** [comment]
If you already use this then I close this
