### ISSUE TITLE
Model Processing Integration

### ISSUE THREAD

**Issue by MrTopom** [simlu/voxelshop#214]
I am working on generation of voxel scenes for my game.

I fact what I did is generated a big vox file with my ground composed of tiles of 16x16x16 voxels. The actual size is 16x16 tiles. So I go around 450.000 voxels and the optimisation and export run fast. That is good.

I'll create a complete scene and see the number of voxels and if I run into issue.

In fact this is the process I would like : Unity Scene Editor -> Generate a scene description in voxels tiles -> Loaded in Voxelshop -> optimized export -> Blender for baking (optional) -> Unity integration as new scene or dynamic loading.

So I need to have Voxelshop able to make this conversion:
- Having Voxelshop listening to some files change in a directory and then load it and convert it based on a description file
- Other idea would be to launch Voxelshop with params and doing batch conversion and then stop working.

In any case I'll put in this issue feedbacks about my progress and some metrics.

**Comment by simlu** [comment]
It seems what you want to use VoxelShop for I mesh optimization. I'm seriously considering separating file conversions out and making them available as a web api...

**Comment by simlu** [comment]
As for your problem: Since you can already compile voxelshop locally, I'd recommend that you create script `main` Java file that does this for you. Should be easiest and fastest solution.

**Comment by MrTopom** [comment]
It could be also a good start for plug-in integration. If I do things with VoxelShop it seems to me better to share things than doing only for me...

**Comment by simlu** [comment]
Please continue discussion here: https://github.com/simlu/voxelshop/issues/38
