### ISSUE TITLE
Non-descriptive Error box 

### ISSUE THREAD

**Issue by bubblefarts** [simlu/voxelshop#225]
Getting an error on windows 10 64bit, no particular description for the error.

Here is the errorlog.txt

[errorlog.txt](https://github.com/simlu/voxelshop/files/857179/errorlog.txt)

**Comment by simlu** [comment]
Interesting one. You using the Java or native installer (exe)? When does the error happen? On start or when you do something else?

**Comment by bubblefarts** [comment]
Error happens right after spalsh screen, I've tried using both the java and native.

**Comment by simlu** [comment]
That sounds like the config might be corrupted. Can you try deleting the ".voxelshop" config folder and try to start voxelshop again?

**Comment by bubblefarts** [comment]
That did it, voxelshop boots up and works fine now,  thank you.
