### ISSUE TITLE
MagicaVoxel .vox format export error

### ISSUE THREAD

**Issue by RichysHub** [simlu/voxelshop#260]
![Comparison image](https://user-images.githubusercontent.com/20910418/31308797-c70de5a0-ab74-11e7-9dce-8f54b08b0071.png)

Image above shows the same model in VoxelShop, and in MagicaVoxel.
As you can see, the model has been flipped.

I believe the error has arisen as VoxelShop is a left handed coordinate system, and MagicaVoxel is right handed. Flipping a single axis direction on the export should fix this.

Model used: [VS_MV comp.zip](https://github.com/simlu/voxelshop/files/1364688/VS_MV.comp.zip)

**Comment by simlu** [comment]
@RichysHub Interesting. Can you give a quick step by step what you are doing to reproduce? Just importing the model?

**Comment by RichysHub** [comment]
Export model from VoxelShop as a MagicaVoxel .vox file (option fit to size is selected)
Open with MagicaVoxel, text is now reversed.
Have verified with my blender import script to make sure error is not with MagicaVoxel
![blender import](https://user-images.githubusercontent.com/20910418/31309002-42c9d5c6-ab77-11e7-90c1-f48fb0f64cce.png)

**Comment by simlu** [comment]
Isn't there a flip option for the export in the voxelshop exporter? I got some time now and will look at this and also at the physics exporter!

**Comment by RichysHub** [comment]
The only export option that supports the flip to right handed coordinate frame is the Qubicle .qb export

**Comment by simlu** [comment]
Right. There are so many exporter and importer. I sometimes confuse them... Magica voxel is relatively new, so there might be an issue there.

**Comment by simlu** [comment]
Fixed in this commit: https://github.com/simlu/voxelshop/commit/81ea08f269120003609677ea5ff066d114af9230

**Comment by simlu** [comment]
@RichysHub Can you confirm this is fixed now please: https://s3-us-west-2.amazonaws.com/voxelshop/build/develop/voxelshop-bin.zip

**Comment by RichysHub** [comment]
Now reading VoxelShop correctly in both
![vs_mv comp fix](https://user-images.githubusercontent.com/20910418/31310348-b0b8e8b2-ab8e-11e7-8e6f-9332cc08a0a3.png)
Looks fixed to me!

**Comment by simlu** [comment]
Sweet!

**Comment by simlu** [comment]
@RichysHub Mind creating a different task for the physics exporter so we can discuss there?
