### ISSUE TITLE
Export Options: Merged / Per Layer / Per Voxel

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#261]
@RichysHub

Will post updates here

**Comment by simlu** [comment]
Basic work done in this commit: https://github.com/simlu/voxelshop/commit/436d83803a7fbcd4da3cf47856bbfbade821e98e

**Comment by simlu** [comment]
@RichysHub Can you confirm please that this works as expected now?

https://s3-us-west-2.amazonaws.com/voxelshop/build/develop/voxelshop-bin.zip

I'm particularly interested if quads are noticeably faster in Blender. If you could compare to your importer and see what changes we still need to make that would be great!

Work remains:
- object center option should be per collada object center (not global center)

**Comment by RichysHub** [comment]
Looks to work great. 
Import time seems to be comparable to my script, certainly the same order of magnitude.
The per object center is a single Blender operation, Set Origin->Origin to Geometry.
I'm not well versed enough to know the quads/tri tradeoffs.
![collada drop](https://user-images.githubusercontent.com/20910418/31310931-7e1f3bd0-ab99-11e7-9703-5ed49c32cc25.gif)

Having the colors being texture based also allows for some effects that are harder to achieve with my importer.

**Comment by simlu** [comment]
Looks very pretty! How long does it take to render?

I've fixed the collada object center positioning in this commit: https://github.com/simlu/voxelshop/commit/a86d8aea07f9ac88b7994510739c685a14d1e2b2

Please test and see if the centers now work as expected!

**Comment by simlu** [comment]
Pre release is up here: https://github.com/simlu/voxelshop/releases/tag/1.8.17
