### ISSUE TITLE
[discussion]Mouse drag and  draws the voxel

### ISSUE THREAD

**Issue by maijz128** [simlu/voxelshop#270]
![2017-10-17_20-34-20](https://user-images.githubusercontent.com/6248618/31665441-6c074a34-b37b-11e7-8cca-53d2588bd745.gif)

**Why is not a command, but a command queue?**

**Comment by maijz128** [comment]
![2017-10-17_20-38-36](https://user-images.githubusercontent.com/6248618/31665454-72008d88-b37b-11e7-814c-2aaa478e6cbc.gif)

**I hope it's like this! Press once to undo.**

**Comment by simlu** [comment]
This is actually by design. However I see where you are coming from. I'll try it out and see how it feels!

**Comment by maijz128** [comment]
I hope  the software can easy to use. 😄
