### ISSUE TITLE
VoxelShop not starting

### ISSUE THREAD

**Issue by easygamer82** [simlu/voxelshop#281]
Hi,

For some reason VoxelShop 1.8.20 is not starting. It shows the loading screen and then, nothing.

I have the Java JDK version 10 x64 installed. I also already tried to delete the settings folder and nothing.

Thank you. :-)

**Comment by simlu** [comment]
Interesting. I haven't tried running it with Java 10. There might be changes required.

Will look into it later.

**Comment by easygamer82** [comment]
Maybe that's why. Might install JSE 8.0 alongside. Thank you. :-)

**Comment by simlu** [comment]
Is there a log file generated by any chance?

**Comment by simlu** [comment]
Yeah settings file would be unrelated. 

Can you try opening the jar file from the console (cmd)? I think it's `java -jar voxelshop.jar`. That should give you an error at least.

It's hard for me to help because I can't reproduce atm.

**Comment by trsh** [comment]
Same thing here. No errors, when run from CMD

**Comment by easygamer82** [comment]
I'm not at home now, so will have to check this at home later...Still, Simlu, do you think it may be due to the program trying to open itself with a bigger resolution than the one supported by my screen?

**Comment by simlu** [comment]
@trsh Do you get a log file? Have you tried deleting your settings file?

@easygamer82 I doubt it very much. There isn't really a minimum resolution.

Can you both send my system specs please. OS Version and exact Java version. I'll try to reproduce over the weekend using vmware.

**Comment by trsh** [comment]
@simlu there is no settings and log file. Just extracted voxelshop  downloaded from Releases.

**Comment by simlu** [comment]
@trsh Settings file would be in your home folder under '.voxelshop' (exact location depending on OS)

**Comment by easygamer82** [comment]
@simlu Sure. It's an Asus Laptop with:

- Core i5-6200U CPU;
- Intel HD graphics 520 / Nvidia Geforce 930M GPU;
- 12GB RAM DDR3;
- Java version 10 (latest one on the Oracle site);
- OS: Windows 10 with latest updates installed (including the Creator's Update).

Thank you.

**Comment by easygamer82** [comment]
@simlu Tested Voxelshop 1.8.20 on my Desktop computer with Java 1.8.0 u161 and it's working. 

My Desktop has a Core i7 920 CPU, a Nvidia GTX 1060 6GB and 8GB DDR3 RAM. Also, the OS is Windows 10 with all the latest updates.

**Comment by Voghelm** [comment]
@simlu hey there. Having absolutely the same issue, have JRE 9 and 10 installed.

Here are my specs:

- 1. Core i5-6200U CPU
- 2. NVIDIA GeForce 940MX
- 3. 8GB RAM
- 4. OS: Win10 PRO x64, updated to the latest version.

Hope this helps!

**Comment by simlu** [comment]
Thanks for all the feedback! So it looks like it might be a problem with Java 9 and 10. I'll see if I can reproduce

**Comment by easygamer82** [comment]
@simlu Even if I run Voxelshop on the CMD, with Java 10, it doesn't create any error report. Go figure. :-)

**Comment by Voghelm** [comment]
@simlu Thanks for responding so quick!

Is there any manual fix we can use right now? Like, trying to run the jar under specific version of java? 

I tried to do this using the java.exe in JRE 8 directory, but it just refuses to run, not even showing the splash screen.

**Comment by simlu** [comment]
If you have Java 8 installed you should be able to select run with under Windows 10 and select that Java version?

**Comment by Voghelm** [comment]
@simlu yep, did exactly that. No effect.  Black command line screen flashes for a second and nothing works.

Java 9 and 10, on the other hand, show the splash screen before that.

Using JRE 8u162

**Comment by simlu** [comment]
Weird. That's exactly what I'm using on windows 10. I'm still at work atm. Will look into it tonight (PST)

**Comment by Voghelm** [comment]
I probably should mention that's I was using x64 installer. I'll do some testing meanwhile, will try out different versions of JRE 8.

**Comment by Voghelm** [comment]
Deleted/reinstalled JRE 8u161/162 in both x86/x64 versions, absolutely the same thing happens.

If I'm trying to use Java 8 it just flashes command prompt window for a moment and then nothing happens. No idea what causes this or why only Java 9/10 somewhat manages to work. Don't really know what else to try, so hope this helps.

**Comment by easygamer82** [comment]
UPDATE: It is an issue with Java 10 and possibly 9 (haven't tried Java 9).

Ok, so I tried to run Voxelshop 1.8.20 through the CMD but, from each of the Java version folders:

- Java 1.8.0 u161: WORKS;
- Java 1.8.0 u162: WORKS;
- Java 10: DOESN'T WORK.

@trsh @Voghelm  The reason why you probably weren't able to run the program through the CMD using the java.exe command is due to the java.exe you're calling is always from a Java version that doesn't work with Voxelshop - most likely version 9 or 10 and likely set on the Windows Environmental Variables panel.

**Comment by simlu** [comment]
Thanks for confirming this! Not expecting the fix to be very involved.

**Comment by Voghelm** [comment]
@easygamer82 Thank you! Now I feel terribly dumb for wasting so much time. 

Made a bat file and now everything runs perfectly under Java 8u162.

**Comment by simlu** [comment]
Good news, I can reproduce. Bad news, I have not idea as to what is going on. The program starts, splash screen starts, but then it shuts down without error. Time for some serious debugging...

**Comment by easygamer82** [comment]
@simlu Godspeed, man. You'll need it. :-)

**Comment by simlu** [comment]
Seems to be this problem: https://stackoverflow.com/questions/48380553/spring-boot-postconstruct-not-called-on-component#answer-48383137

**Comment by simlu** [comment]
Oh boy. At some point we'll need to update JIDE. Not looking forward to that ... sigh

I'll do a release here shortly so we can at least use in java 9 and 10

**Comment by simlu** [comment]
Ok, I've done the release here: https://github.com/simlu/voxelshop/releases

Please let me know if that fixes it for you (you might also get some warnings in the console?)

**Comment by trsh** [comment]
Works on java 9.x! Thanks!

Btw is there some doc or tut how to work with animations?

**Comment by Voghelm** [comment]
Everything works on Java 10 as well. Thanks for the speedy fix!

**Comment by simlu** [comment]
Great! Thanks for confirming! Got a little lucky to figure out what was going on as quickly as I did.

@trsh Animation support is not fully implemented. Feel free to contribute to the discussion here
