### ISSUE TITLE
[Linux] Export form unusable on smaller monitor

### ISSUE THREAD

**Issue by Garrom** [simlu/voxelshop#286]
Hi @simlu , Do you remember the issue #274 ? Near the end you done some magic with export form so it fit to my monitor. Well, this magic does not work on Linux. Can you do something with it please ?
![snimek z 2018-04-17 14-07-46](https://user-images.githubusercontent.com/24418090/38869817-385f5950-424c-11e8-8503-6c7cba196210.png)

**Comment by simlu** [comment]
I do remember! Thanks for reporting!

What is your exact Linux distribution and what window manager do you use?

**Comment by Garrom** [comment]
@simlu  I using Ubuntu 16.04. For windows(and desktop and panel and quite everything) Gnome 3.18.5.
It is kinda strange because Java is supposed to work same no matter where you launch application.

**Comment by simlu** [comment]
Kk, that should give me something to test! Also forget to ask what resolution you're running. I guess I can look at the screenshot.

Well, cross platform is the promise. Not entirely true unfortunately from experience. But it works ok for the most part. Linux, Windows, OSX are very different environments to be fair.

Ill try to look into this over the weekend. Pretty busy atm

**Comment by Garrom** [comment]
@simlu  Thanks. My resolution is 1366x768, it is quite standard for mid-end laptops

**Comment by Garrom** [comment]
@simlu I'm very late to this. Now using Ubuntu 18.04 with XFce. You can close this issue, it works fine. I remember why I did not reported back. Some time ago I was switching between Windows and Ubuntu like crazy. I was trying to find what system suits me best. I thought is embarrassing to say "Oh, I don't know if it works because I'm using windows for this week but I don't think I'll use it for long". Ultimately, I settled down with Ubuntu 16.04 (was later upgraded to 18.04) and XFce.
