### ISSUE TITLE
Importing layers as separate meshes to Blender

### ISSUE THREAD

**Issue by Shaanig01** [simlu/voxelshop#292]
I'm trying to create a voxel character but I just realized that you can only export them as a single mesh. I want the layers I created imported to blender as separate meshes. I tried picking 3 options in "Object Separation" located in the export ui of voxelshop, "Per Layer", "Per Voxel" and "Merge". 3 of em just yields the same result, its still one mesh. I'm on Alpha Version(1.8.24). I thought "Per Layer" was the way to go.

**Comment by simlu** [comment]
This should work as expected (I just tested it). Can you provide screenshots of (1) the layers in voxelshop, (2) the export dialog and (3) the object view in blender after importing? There has to be a mistake in there somewhere

**Comment by Shaanig01** [comment]
I did something wrong, I quickly tested out if this program can import separate meshes and I think have might done it all in one layer. I actually come from MagicaVoxel, had to switch because it can't import separate meshes, very sorry for disturbing your time. Should have payed more attention to layers.

**Comment by simlu** [comment]
Kk, np at all! Feel free to open another ticket if you have questions!
