### ISSUE TITLE
Add install.sh for linux - see bash script in comment 

### ISSUE THREAD

**Issue by poikilos** [simlu/voxelshop#296]
Hello, I'm not sure where to put this for a pull request, but I hope that you can make use of this. 

### Actual Behavior
Cannot double-click jar files in linux (not voxelshop's fault)

### Expected Behavior
Unzip then use voxelshop without terminal, or at least have install.sh script to get a GUI icon.

* This script can be placed in the voxelshop directory in the zip file.
* If PREFIX environment variable is not set, the script uses $HOME/.local (if EUID is 0 [running as root] then /usr/local instead)
* The script uses following directories under the PREFIX according to standards: $PREFIX/lib/voxelshop/, $PREFIX/bin/, $PREFIX/share/applications/, $PREFIX/share/pixmaps/
* I attached the script to avoid issues with copying and pasting from the web:
[install.sh.tar.gz](https://github.com/simlu/voxelshop/files/3031503/install.sh.tar.gz)

#### You would also have to add the following to the linux zip builds:
* You'll have add the existing resource/img/icons/application/icons/icon-48x48.png to a  **voxelshop/share/pixmaps** directory (or other location, see shortcut_path variable)
* The attached shortcut file (tar.gz'd desktop file) is needed as well, in the **voxelshop/share/applications** directory (or other location--see icon_src_path variable)--the install script rewrites the Exec and Icon variables according to PREFIX before installing the shortcut.
[com.blackflux.voxelshop.desktop.tar.gz](https://github.com/simlu/voxelshop/files/3031323/com.blackflux.voxelshop.desktop.tar.gz)

**Comment by simlu** [comment]
Hello @poikilos!

Thank you very much for your input here! Much appreciated and I would love to include this. Have a few questions first though:

1) How would one go about uninstalling (reverting the installation process)?
2) What did you base your script on? I'm assuming you didn't write this all from scratch?
3) Would you be able to create an example linux distribution zip file that I can use as an example? That would make it much easier for me to set it up.

Cheers, L~

**Comment by poikilos** [comment]
1. There is no uninstall. This is expected for installing from source unless autotools or another framework is used for generating a manifest.
2. I wrote this all from scratch, with trivial syntax help from stackoverflow as usual. Some of it (such as application menu refreshing) is boilerplate from my other projects. I worked as a linux server admin for a while, and all installs that weren't packaged were automated like this. I wrote the script for VoxelShop because I like it so want to encourage development and help my friends install it.
3. See attached (same as your zip, but with necessary files and the install script--this would be a good way to distribute it to linux users)
[voxelshop.tar.gz](https://github.com/simlu/voxelshop/files/3036310/voxelshop.tar.gz)

**Comment by poikilos** [comment]
Ok, now it creates an install.log and has an uninstall.sh. Enjoy...
[voxelshop-1.8.24.tar.gz](https://github.com/simlu/voxelshop/files/3036495/voxelshop-1.8.24.tar.gz)

**Comment by simlu** [comment]
@poikilos Sweet, thank you very much! I'll try to review and add it this weekend!

**Comment by simlu** [comment]
@poikilos Finally had time to review this. Looking good!

I've opened a pr here: https://github.com/simlu/voxelshop/pull/298/files

However ideally we would detect if we "should" install. I.e. fail on windows. The alternative is to have different distros, but I'm not a big fan. What do you think?

**Comment by poikilos** [comment]
I'm not sure what you mean by "fail on Windows." This file would be excluded from windows builds if possible. Is that what you mean by different distros? I see if you want to avoid that. However, maybe just add a big banner for Windows users at the top of the sh file:
```bash
#!/bin/sh


# To install on Windows:
# * Make sure you have clicked "Extract All" first
# * right-click on the jar file, then click Send to, Desktop (Create Shortcut)



```

**Comment by simlu** [comment]
I've released it as a pre-release: https://github.com/simlu/voxelshop/releases

Let me know if everything looks good and I'll make it a full release!

**Comment by poikilos** [comment]
Pretty good so far! I am sending a PR to deal with the following:
* The icon works, but only if java is installed. Often only a "headless' java is installed in linux (such as Ubuntu and Fedora), leading to the program not opening. The best way to deal with this is to change the voxelshop bin to send a notification to the user if it fails to run.
* /usr/local/share/pixmaps/voxelshop.png is not being installed, so though the shortcut works, the icon is blank.
I have verified that the PR resolves both issues.

**Comment by poikilos** [comment]
Ignore the first PR on my repo, I accidentally submitted a PR to myself! The open PR #299 is the valid one.

**Comment by simlu** [comment]
@poikilos Merged and did another release. I'll mark it as a full release once you confirm that everything looks good!

**Comment by simlu** [comment]
Closing, but feel free to comment if there are any issues!
