### ISSUE TITLE
From voxelshop to blender (cycles)

### ISSUE THREAD

**Issue by MunMun2** [simlu/voxelshop#297]
Is there a way to export a model from voxelshop to blender, so that the textures won't be messed up and would work with cycles render?

**Comment by simlu** [comment]
@MunMun2 Yes, there certainly is. I think you need to adjust the model after each import though.

Let me see if I can dig up the instructions somewhere... I'll get back here in an hour or so.

**Comment by simlu** [comment]
Sorry for the late reply. Things side tracked a little... The forum is completely broken, but there is still lots of useful info on there: https://blackflux.com/forums/viewtopic.php?f=9&t=108 (fixing that is another project arg)...

You should be able to modify the export options and / or blow up the textures if you still have problems after following those instructions.

**Comment by simlu** [comment]
Closing this. Feel free to comment if you have further issues!
