### ISSUE TITLE
Extend Bounding Box beyond 128.

### ISSUE THREAD

**Issue by PanTrakX** [simlu/voxelshop#306]
Is it possible to extend the bounding box beyond 128?

**Comment by simlu** [comment]
Sorry, I missed this. I don't think there currently is. What use case are you trying to support?

**Comment by PanTrakX** [comment]
Hello @simlu!

> What use case are you trying to support?

I wanted to extend the bounding box so i can add more than 128 per axis since I am making "high resolution" voxel models!

Anyways I closed the issue since I don't use VoxelShop anymore, i found other voxel editors that fit my needs better!

Thanks for you time! :)

**Comment by simlu** [comment]
Thanks for the reply! 

Yeah voxelshop is not well suited for high res. Good luck with whatever you're using now 😉
