### ISSUE TITLE
I can not open voxelshop

### ISSUE THREAD

**Issue by Wi5p** [simlu/voxelshop#307]
I can not open voxelshop, because I can not choose through what to open the file "jar", what kind of program do I need to select to open it?

**Comment by simlu** [comment]
Uhm... You need too have Java installed.

If you have Java installed, clicking the script should start voxelshop. Is that not working?

**Comment by Wi5p** [comment]
> Гм ... У вас тоже должна быть установлена ​​Java.
> 
> Если у вас установлена ​​Java, щелчок по сценарию должен запустить voxelshop. Это не работает?

the problem is that I ran it 1 time without Java (I forgot to install it after reinstalling) and accidentally launched it through another program, plus with a checkmark that always use it, then I tried to select Java where it is installed, but this Does not help

**Comment by simlu** [comment]
Are you on Windows? I'm sure if you google "how to remove default program for file extension", something will come up!

**Comment by Wi5p** [comment]
It was possible to remove the program for the extension, but now you just need to reinstall the archive and try to run it?

**Comment by Wi5p** [comment]
I tried to reinstall the program and Java, but the problem is that now it is not clear through what to open, I tried it through the Java application, nothing happens, some applications turn on the console for a moment and that's it

**Comment by Wi5p** [comment]
I almost succeeded, I partially solved it in this way: Open notepad.exe
Write: java -jar Example.jar
Save it with a .bat extension
Copy it to the directory where the .jar file is located
Double click it to run the .jar file
But it gives an erro
![java_iPYgZ5JW4x](https://user-images.githubusercontent.com/95759603/146182540-ca9825ad-a165-4705-a79f-21410ead091a.png)
r

**Comment by simlu** [comment]
There should be an error file generated, what's in it? Which Java version are you using?

**Comment by Wi5p** [comment]
java- jdk17.0.1
file java -jar voxelshop-start.jar

**Comment by simlu** [comment]
And the error log? Voxelshop might not be compatible with the latest Java version (I'm not sure tbh)

**Comment by Wi5p** [comment]
And what version of Java is better to put?

**Comment by simlu** [comment]
Without the error log it's hard to know the reason. You could try Java 8?

**Comment by Wi5p** [comment]
ok

**Comment by Wi5p** [comment]
but how to open the error log?

**Comment by Wi5p** [comment]
The problem was solved, it was enough to install version 8 of Java, for those who encounter a similar problem I will leave a link to Java:https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html
