### ISSUE TITLE
Add *.vox (MagicaVoxel) exporter

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#31]
And I guess this one is missing... I wish there were fewer file formats...

**Comment by simlu** [comment]
Reference (there was another):
https://blackflux.com/forums/viewtopic.php?f=9&t=22#p91

**Comment by MrTopom** [comment]
Ref: https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt

It is indexed palette oriented with only 255 colors. So we'll have to find how the conversion will be done is more colors.

I did already a small VOX partial export (not material, no palette) in java to test my first procedural attempt.

**Comment by simlu** [comment]
There is already an importer. Maybe good to look at that for an example!

**Comment by Zireael07** [comment]
Upvoting since this would be really helpful.

**Comment by simlu** [comment]
Note: Use the binary comparator that comes with VoxelShop to ensure input equal output file once you have something working.

**Comment by simlu** [comment]
I think we also want the option to use the bounding box for the chunk size... What do you think?

**Comment by simlu** [comment]
Created a pull request with some changes and fixes to your pull request here: https://github.com/funabab/voxelshop/pull/1

Let me know what you think! @funabab

**Comment by simlu** [comment]
Adding a bounding box option should be easy. [QbExporter.java](https://github.com/simlu/voxelshop/blob/master/PS4k/src/com/vitco/export/QbExporter.java) shows pretty much exactly how to do it.

**Comment by simlu** [comment]
Was worked on here: https://github.com/simlu/voxelshop/pull/206

I still want to add a "bounding box as chunk" option...

**Comment by simlu** [comment]
Can you please review this pull request @funabab: https://github.com/simlu/voxelshop/pull/208

Once that is merged this task can be closed.

**Comment by simlu** [comment]
This is done and merged now.

**Comment by simlu** [comment]
Will be live with Version 1.9.0
