### ISSUE TITLE
Shortcut for Deselecting

### ISSUE THREAD

**Issue by skyezeno** [simlu/voxelshop#52]
Ability to Deselect selection with CTRL+SHIFT+A

**Comment by simlu** [comment]
You just press 'escape' for deselecting. Does that do what you want? You can customize the shortcut in the shortcut manager.

**Comment by skyezeno** [comment]
Thanks does exactly what i wanted. Kinda used to other programs using that shortcut.

**Comment by simlu** [comment]
Interesting. Which other program does this?
