### ISSUE TITLE
Option to select visible Voxel over all layers

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#67]
Similar to how CTRL + A currently works for the selected layer

**Comment by simlu** [comment]
Basically this is already implemented, but only for selecting voxels in current layer.

Have a look at the shortcuts.xml file and then how the action is defined. Then create your own action (very similar) and bind it to a new shortcut (not sure yet what it should be, maybe ctr + shift + a?).

**Comment by MrTopom** [comment]
Done.

**Comment by simlu** [comment]
Merged and live with the Java version
